### ISSUE TITLE
Correct method for setting viewport with `BoxingViewportAdapter`.

### ISSUE THREAD

**Issue by c272** [Ellpeck/MLEM#1]
Hello,

I'm using MLEM.Ui to make a personal game project, and so far it's been great, however I'm having a small issue with the viewport system interacting with the `BoxingViewportAdapter` from MonoGame.Extended. When my window resizes to a resolution that is not exactly 16:9 (which is my target aspect ratio using the `BoxingViewportAdapter`, which has it's virtual resolution set to 1280x720), I was initially updating the viewport of the system like so:

```
uiSystem.Viewport = ViewportAdapter.Viewport.Bounds;
```

However, this resulted in the UI being offset by `(x, y)` from the top left of the viewport, where the amount was equal to `Viewport.Bounds.Location` (image below), clipping the UI into the bottom of the screen, however at this stage the input handler was detecting hovering over the buttons at the correct locations (viewport indicated in red here, although it extends past the bottom of the clipped region).

![Incorrect Viewport Offset](https://i.imgur.com/3RD7IZw.png)

To fix this visual offset, I have tried both setting the viewport's `Location` to (0, 0), and also creating a translation matrix applied to all top level elements (eg. `Matrix translate = Matrix.CreateTranslation(-newVP.X, -newVP.Y, 0)`). Both of these approaches do work, however this results in the input handling for the UI being offset incorrectly by the amount of the translation.

What is the correct way to implement this viewport adjustment without either compromising the input handler or the GUI's visual location?

**Comment by Ellpeck** [comment]
In general, the input isn't offset by anything other than the ui system's viewport, so this issue sounds a little weird. I have not used a viewport with a position offset yet, though, so I will try to play around with it soon!

It might also be possible that MonoGame.Extended's viewports change additional MonoGame settings (like mouse position offsets for example) under the hood. If that was the case, it would also explain this discrepancy.

**Comment by Ellpeck** [comment]
Build 364 of MLEM and MLEM.Ui (https://nuget.ellpeck.de/packages/mlem/5.3.0-364 and https://nuget.ellpeck.de/packages/mlem.ui/5.3.0-364) should contain a fix that makes the ui's input handling take the game's viewport into account by default. This also means that there shouldn't be a discrepancy when changing the ui system's viewport manually anymore, either.

**Comment by c272** [comment]
Thank you very much, updated to the latest prerelease build & my transformations work perfectly.
