### ISSUE TITLE
MonoGame freezes when passing non square region to NinePatch

### ISSUE THREAD

**Issue by rallianto** [Ellpeck/MLEM#17]
This will run fine:
PaperBorderPatch = new NinePatch(new TextureRegion(UITextureAtlas, 128, 0, 64, 64), 16, NinePatchMode.Tile);
Where the region is 64x64

But when this is passed
PaperBorderPatch = new NinePatch(new TextureRegion(UITextureAtlas, 128, 0, 64, 32), 16, NinePatchMode.Tile);
Where the region is 64x32, MG freezes

**Comment by Ellpeck** [comment]
This is likely because you set your texture height to 32 pixels, but your padding width and height to 16 as well, causing the total height of the rendered texture region to be 0. While this shouldn't cause the program to hang, it *also* shouldn't be something that is valid to do.
