### ISSUE TITLE
UiSystem.Draw throws System.MissingMethodException in FontStashSharp

### ISSUE THREAD

**Issue by asik** [Ellpeck/MLEM#21]
UiSystem.Draw throws

> System.MissingMethodException: 'Method not found: 'Single FontStashSharp.SpriteFontBase.DrawText(Microsoft.Xna.Framework.Graphics.SpriteBatch, System.String, Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Color, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, Single, Microsoft.Xna.Framework.Vector2, Single, Single, Single, FontStashSharp.TextStyle, FontStashSharp.FontSystemEffect, Int32)'.'

What I did:

- Create a new Monogame 3.8.1 WindowsDX project 
- Add the following nuget packages:
  - MLEM (6.2.0)
  - MLEM.UI (6.2.0)
  - MLEM.Extended (6.2.0)
  - FontStashSharp.MonoGame (1.3.6)
- Add a ttf font file
- Add the following code to LoadContent (mostly from https://mlem.ellpeck.de/articles/ui.html#adding-elements):

```csharp
_fontSystem = new FontSystem();
_fontSystem.AddFont(File.ReadAllBytes(@"Content/Fonts/12-post-antiqua-roman-05554.ttf"));

var style = new UntexturedStyle(_spriteBatch)
{
    Font = new GenericStashFont(_fontSystem.GetFont(18))
};
MlemPlatform.Current = new MlemPlatform.DesktopGl<TextInputEventArgs>((w, c) => w.TextInput += c);
_uiSystem = new UiSystem(this, style);
var box = new Panel(Anchor.Center, new Vector2(100, 1), Vector2.Zero, setHeightBasedOnChildren: true);
box.AddChild(new Paragraph(Anchor.AutoLeft, 1, "This is some example text!"));
box.AddChild(new Button(Anchor.AutoCenter, new Vector2(0.5F, 20), "Okay")
{
    OnPressed = element => _uiSystem.Remove("InfoBox"),
    PositionOffset = new Vector2(0, 1)
});
_uiSystem.Add("InfoBox", box);
```
The following code to Update:

```csharp
_uiSystem.Update(gameTime);
```

And the following to Draw:

```csharp
_uiSystem.Draw(gameTime, _spriteBatch);
```

FontStashSharp seems to be working on its own, I can do `.DrawText` and it works.

**Comment by Ellpeck** [comment]
Hi, thanks for your in-depth report!

This is unfortunately due to a recent-ish breaking change in FSS which I already addressed [in-dev](https://github.com/Ellpeck/MLEM/commit/6a8e9639c163f637d140bc89e9283268b23d1338). You can either downgrade FSS, or use a prerelease version of MLEM from the [private feed](https://nuget.ellpeck.de).
