### ISSUE TITLE
Wobbly text doesn't animate if it's formatting the first character in a string

### ISSUE THREAD

**Issue by all-iver** [Ellpeck/MLEM#26]
This does not animate: `"<a wobbly>This is a formatted string!</a>"`

Workaround is to add some formatter padding: `"<b></b><a wobbly>This is a formatted string!</a>"`

**Comment by Ellpeck** [comment]
*note to self*: turns out this happens because the first code isn't added to the `allCodes` collection because it's handled separately: https://github.com/Ellpeck/MLEM/blob/main/MLEM/Formatting/TextFormatter.cs#L164
