### ISSUE TITLE
Calculating real index within `Code.DrawCharacter`

### ISSUE THREAD

**Issue by c272** [Ellpeck/MLEM#3]
Currently, the `DrawCharacter` function in `Code` has the following function signature:
```
bool DrawCharacter(GameTime time, SpriteBatch batch, char c, string cString, int indexInToken, ref Vector2 pos, GenericFont font, ref Color color, ref float scale, float depth)
```

I'm trying to implement a system which slowly reveals text over time, and since the token index provided as a parameter here (`indexInToken`) resets at the start of every new token, which can be caused by any number of other codes, there doesn't seem to be a way to discern what index within the entire scope that the `Code` applies to the character is at, and I need this information to determine whether enough time has passed to reveal this character or not.

For example; if I have the following text passed into the formatter:
```
<reveal 0.5>This is some text <u>that's being revealed!</u></reveal>
```
There doesn't seem to be a way for me to discern the first "T" character from "This" (real index 0) and the lowercase "t" from "that's" (real index 19) within the `DrawCharacter` function, as they both have a token index of 0, since the underline starts a new token. If the class had access to the raw index/index of the token that was being rendered at the time this would be fine, but I don't see any way to access that information.

Am I misjudging how the system works here? Is there a way for me to calculate the literal index of the character being drawn?
Apologies for the long issue.

**Comment by Ellpeck** [comment]
You can use `Token.Index` or alternatively `Token.RawIndex` to get the total index of the start of the code's application range. You can see this being done in [WobblyCode](https://github.com/Ellpeck/MLEM/blob/main/MLEM/Formatting/Codes/WobblyCode.cs#L32).

**Comment by c272** [comment]
I saw that, but I don't understand how that will help me figure out where the character that's currently being drawn is within the code's application range, since this isn't the token currently being drawn, it's just the token that the `Code` applies till/from.

**Comment by Ellpeck** [comment]
Aah, I see what you mean. Yes, when an additional formatting code is added, a new token is started with the same code. I'll think of a solution for that.

**Comment by Ellpeck** [comment]
Let me know if this works as expected once you get around to testing, if you can!

**Comment by c272** [comment]
Thank you for the speedy update! The new property works great, apart from when a token crosses a newline. Taking a look at `TokenizedString.cs` ([here](https://github.com/Ellpeck/MLEM/blob/main/MLEM/Formatting/TokenizedString.cs#L=128)), it seems that the token index passed in is relative to the line in the `SplitDisplayString`, rather than being the literal index in that token.

**Comment by Ellpeck** [comment]
Ah, I see. That should be an easy fix!

**Comment by c272** [comment]
Thank you very much, this works perfectly now! 🙏
